fix: Fixed syntax error in comment and added PyYAML
PROBLEMS:
1. Syntax error: Comment had extra '...' at end
   '# ETAPE 3 : Installation des paquets Python...'
   Should be just: '# ETAPE 3 : Installation des paquets Python'

2. Missing PyYAML dependency
   Error: 'no module named yaml'

FIXES:
- Removed invalid '...' from comment
- Added PyYAML to packages list

NO MORE SYNTAX ERROR!